NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index  # Выбрана рабочая папка NewsPaper в меню папки: "Mark Directory as"
from news.views import page_not_found, user_not_authenticated
from accounts.views import IndexView

# Для кэширования
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('', cache_page(60)(index), name="home"),  # Добавлено кэширование главной страницы, 1 мин
    path('protect/', IndexView.as_view(), name="login_redirect_url"),
    path('accounts/', include('accounts.urls')),
    path('account/', include('allauth.urls')),  # это при помощи pip install django-allauth
    # path('', Index.as_view(), name="home"),
]

handler404 = page_not_found  # Теперь при ошибке 404 будет наша запись, а не стандартная, есть handler для др. ошибок
handler403 = user_not_authenticated

NewsPaper/news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import NewsList, PostDetail, SearchNewsList, NewsCreate, ArticlesCreate, NewsUpdate, NewsDelete, \
   ArticlesUpdate, ArticlesDelete, check_category, ProbaCelery

# Для кэширования
from django.views.decorators.cache import cache_page

urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('', cache_page(60*5)(NewsList.as_view()), name='news'),  # Добавлено кэширование на страницу с новостями, 5мин
   # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
   # int — указывает на то, что принимаются только целочисленные значения
   path('<int:id>', PostDetail.as_view(), name='post'),
   path('search/', SearchNewsList.as_view(), name='news_search'),
   path('news/create/', NewsCreate.as_view(), name='news_create'),
   path('articles/create/', ArticlesCreate.as_view(), name='articles_create'),
   path('news/<int:pk>/edit/', NewsUpdate.as_view(), name='news_update'),
   path('articles/<int:pk>/edit/', ArticlesUpdate.as_view(), name='articles_update'),
   path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
   path('articles/<int:pk>/delete/', ArticlesDelete.as_view(), name='articles_delete'),
   # path('mail/', Mailing.as_view(), name='mailing')
   path('category/', check_category, name='check_category'),
   path('cel/', ProbaCelery.as_view(), name='ProbaCelery'),
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.cache import cache  # Для кэширования


class Author(models.Model):  # объекты всех авторовuse
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, verbose_name='Автор')
    rating = models.IntegerField(default=0, null=True, verbose_name='Рейтинг')

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        ordering = ['id', 'user_id']

    def update_rating(self):
        self.rating = 0
        for i in Post.objects.all().values('user_id', 'rating'):
            if self.user_id == i.get('user_id'):
                self.rating += i.get('rating') * 3 if self.rating > 0 else (self.rating + 1) * i.get('rating') * 3

        for i in Comment.objects.all().values('rating', 'user_id'):
            if self.user_id == i.get('user_id'):
                self.rating += i.get('rating')

        post_user = Post.objects.filter(user_id=self.user_id).values("id")
        # Сдается, что это можно было сделать изящней
        for i in Comment.objects.all().values('rating', 'post_id'):
            for j in post_user:
                if j.get('id') == i.get('post_id'):
                    self.rating += i.get('rating')

        self.save()

    def __str__(self):
        return f"{self.user}"


class Category(models.Model):  # Категории новостей/статей — темы
    SPOTS = 'SP'  # определяются внутри класса
    POLICY = 'PO'
    EDUCATION = 'ED'
    TECHNIQUE = 'TE'
    SCIENCE = 'SC'
    NATURE = 'NA'
    INTERNET = 'IN'
    OTHER = 'OT'

    CATEGORY = [
        (SPOTS, 'Спорт'),
        (POLICY, 'Политика'),
        (EDUCATION, 'Образование'),
        (TECHNIQUE, 'Техника'),
        (SCIENCE, 'Наука'),
        (NATURE, 'Природа'),
        (INTERNET, 'Интернет'),
        (OTHER, 'Прочее')
    ]

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

    title = models.CharField(max_length=2, choices=CATEGORY, default=OTHER, unique=True, verbose_name='Категории')

    def __str__(self):
        return f"{self.title}"


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usersabscr', verbose_name='Пользователь')
    subscribers = models.ForeignKey(Category, to_field='title', on_delete=models.CASCADE, related_name='categories', verbose_name='Подписка', null=True)

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ['user']

    def __str__(self):
        return f'{self.user}: {self.subscribers}'


# Нужно вынести в отдельный файл
NEWS = 'NW'
ARTICLE = 'AR'
TYPE_ARTICLE = [(NEWS, 'Новость'), (ARTICLE, 'Статья')]


class Post(models.Model):  # содержит в себе статьи и новости, которые создают пользователи
    user = models.ForeignKey(Author, to_field='user_id', on_delete=models.CASCADE, verbose_name='Автор')  # Связь с автором
    type_article = models.CharField(max_length=2, choices=TYPE_ARTICLE, default=ARTICLE, verbose_name='Тип')  # поле с выбором статья или новость, по умолчанию - статья
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    category = models.ManyToManyField(Category, through='PostCategory')  # Связь с категориями
    title = models.CharField(max_length=200, verbose_name='заголовок')  # Заголовок
    article = models.TextField()  # Текст статьи/новости
    rating = models.IntegerField(default=0, null=True, verbose_name='рейтинг')

    class Meta:
        verbose_name = 'Публикация'  # Название модели для админ панели
        verbose_name_plural = 'Публикации'  # Тоже самое для множественного числа
        ordering = ['id', 'user']  # Сортировка в админ панели по id и user, в список можно добавить еще параметры

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        pr = self.article[:124]
        return pr + ' ...'

    def __str__(self):
        return f'{self.title[:15]}: {self.id}'  # : {self.article}'

    def get_absolute_url(self):
        return reverse(viewname='post', args=[str(self.id)])

    # Для кэширования на странице с новостью.
    # Установили реакцию на редактирование объекта. Когда объект меняется его надо удалять из кэша,
    # чтобы ключ сбрасывался и больше не находился.
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'news-{self.id}')  # затем удаляем его из кэша, чтобы сбросить его


class PostCategory(models.Model):  # Промежуточная модель для связи «многие ко многим»
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Категория публикации'
        verbose_name_plural = 'Категории публикаций'
        ordering = ['id', 'post_id', 'category_id']


class Comment(models.Model):  # комментарии к новостям/статьям
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    com_text = models.TextField(verbose_name='Содержание')  # Текст комментария
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    rating = models.IntegerField(default=0, null=True, verbose_name='Рейтинг')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['id', 'post_id', 'user_id', 'date_create']

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post, Category, Subscription, Author


class CategoryForm(forms.Form):
    title = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='ничего', label='Категории', widget=forms.CheckboxSelectMultiple)
    # cat = forms.CheckboxInput.get_context(attrs=Category.objects.all().values('title'))
    # class Meta:
    #     model = Category
    #     fields = ['title', ]
    #     # model = Subscription
    #     # fields = ['user', 'subscribers', ]


class NewsForm(forms.ModelForm):
    # user = forms.ChoiceField(label='Автор', choices='user')
    # category = forms.ChoiceField(label='Категория', choices=Category.CATEGORY)
    # title = forms.C(label='Заголовок')
    # article = forms.Textarea(label='Содержание')

    def us(self, request):
        _user = request.user
        return _user

    user = us

    class Meta:
        model = Post
        # exclude = ['user']  # Исключить поле
        widgets = {
            'category': forms.CheckboxSelectMultiple,
            'title': forms.Textarea(attrs={'class': 'form-text', 'cols': 150, 'rows': 3}),
            'article': forms.Textarea(attrs={'class': 'form-text', 'cols': 150, 'rows': 10}),
        }
        labels = {
            'category': 'Категории',
            'article': 'Содержание',
        }
        fields = [
            'user',
            'category',
            'title',
            'article'
        ]

    # хз зачем, в модели эти поля определены как не могут быть пустыми по умолчанию
    def clean(self):
        cleaned_data = super().clean()
        user = cleaned_data.get("user")
        if user is None:  # проверка
            raise ValidationError({
                "user": "Должен быть хотя бы один символ"
            })

        # category = cleaned_data.get("category")
        # if category is None:
        #     raise ValidationError({
        #         "category": "Должен быть хотя бы один символ"
        #     })

        title = cleaned_data.get("title")
        if title is None:
            raise ValidationError({
                "title": "Должен быть хотя бы один символ"
            })

        article = cleaned_data.get("article")
        if article is None:
            raise ValidationError({
                "article": "Должен быть хотя бы один символ"
            })

NewsPaper/templates/news/articles_delete.html
{% extends 'news/flatpages/default.html' %}

{% block content %}
<div class="post">
<h1>Удаление статьи</h1>
<hr>
{% if object.type_article == "AR" %}
<form action="" method="post">
    {% csrf_token %}
    <p>Вы действительно хотите удалить публикацию? <br><br> Заголовок: <br> "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% else %}
    <div align="left">
        <ul>
            <li> Новости редактируются на другой странице </li>
        </ul>
    </div>
{% endif %}
</div>
{% endblock content %}

NewsPaper/templates/news/articles_edit.html
{% extends 'news/flatpages/default.html' %}

{% block title %}
Форма записи
{% endblock title %}

{% block content %}
<div class="post">
<h3> Публикация/редактирование</h3>
<p style="font-size:22px"> статьи </p>
<hr>
{% if object.type_article == "AR" or object.type_article is None %}
    <div align="left">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" />
        </form>
    </div>
{% else %}
    <div align="left">
        <ul>
            <li> Новости редактируются на другой странице </li>
        </ul>
    </div>
{% endif %}
<hr>
{% if object.id is not None%}
    <p align="left"><a href="{% url 'articles_delete' post.id %} " > Удалить статью </a></p>
{% endif %}
</div>
{% endblock content %}

NewsPaper/templates/news/category_subscr.html
{% extends 'news/flatpages/default.html' %}

{% block title %}
Подписка
{% endblock title %}

{% block content %}
<!--
<style>
p,
label {
  font:
    1rem 'Fira Sans',
    sans-serif;
}
input {
  margin: 0.4rem;
}
</style>
-->
<div class="post">
<div align="left">
    <form action="" method="POST">
        {% csrf_token %}

        <p>{{ form.as_p }}</p><br>
        <p>{{user}}</p>
        <input type="submit" value="Подписаться">
    </form>
</div>
</div>
{% endblock content%}

NewsPaper/templates/news/index.html
{% extends 'news/flatpages/default.html' %}

<!-- Название у нас будет -->
{% block title %}
Главная
{% endblock title %}

<!-- В контенте на странице мы выводим все новости -->
{% block index %}
<!-- <h1> Новостной портал </h1> -->

    {% include 'accounts/users_auth.html' %}

<!-- <p><a href="/news/"> Читать полностью ... </a></p> -->

{% endblock index %}
{% block content %}
<style>
    .red {
        color: red;
    }
    .stalin {
        text-indent: 30px;
        text-align: justify;
    }
</style>
<div class="post">
    <p class="stalin">
        «Необходимо добиться такого культурного роста общества, который бы обеспечил всем членам общества всестороннее развитие их физических и умственных способностей, чтобы члены общества имели возможность получить образование, достаточное для того, чтобы стать активными деятелями общественного развития, чтобы они имели возможность свободно выбирать профессию, а не быть прикованными на всю жизнь, в силу существующего разделения труда, к одной какой-либо профессии.
        Что требуется для этого? Было бы неправильно думать, что можно добиться такого серьезного культурного роста членов общества без серьезных изменений в нынешнем положении труда. <span class="red"> Для этого нужно прежде всего сократить рабочий день по крайней мере до 6, а потом и до 5 часов.</span>
    </p>
    <p class="stalin">
        Это необходимо для того, чтобы члены общества получили достаточно свободного времени, необходимого для получения всестороннего образования. Для этого нужно, далее, ввести общеобязательное политехническое обучение, необходимое для того, чтобы члены общества имели возможность свободно выбирать профессию и не быть прикованными на всю жизнь к одной какой-либо профессии. Для этого нужно, дальше, коренным образом <span class="red">улучшить жилищные условия и поднять реальную зарплату</span> рабочих и служащих минимум вдвое, если не больше, как путем прямого повышения денежной зарплаты, так и, особенно, путем дальнейшего <span class="red">систематического снижения цен</span> на предметы массового потребления.»
    </p>
    <p class="stalin">
        Сталин И.В. 1952г
    </p>
</div>
{% endblock content %}

NewsPaper/templates/news/mailing.html
{% extends 'news/flatpages/default.html' %}

{% block title %}
Новость
{% endblock title %}

{% block content %}
<div class="post">
<h1> Вы подписаны на рассылку </h1>
<br>
<br>
<br>
<a href="\">  На главную </a>
</div>
{% endblock content %}

NewsPaper/templates/news/news.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'news/flatpages/default.html' %}

{% load app_filters %}
<!-- для пагинации, см. custom_tags.py -->
{% load custom_tags %}

<!-- Название у нас будет -->
{% block title %}
Публикации
{% endblock title %}

<!-- В контенте на странице мы выводим все новости -->

{% block preview %}
<div class="post">
    <!-- <style>
        li { list-style-type: none; }
        .news_bar {
        background: #ebe4e4;
        }
    </style> -->  <!-- Убираем маркеры в списке -->
    <h3> {{ time_now|date:'d F Y' }}</h3>
    <h4> {{ next_sale|default_if_none:"Приветствуем на новостном портале" }} </h4>
    <div align="right">
        <ul>
            <li> Новость:<a href="{% url 'news_create' %}" style="text-decoration: none"> создать </a> </li>
            <li> Статью:<a href="{% url 'articles_create' %}" style="text-decoration: none"> создать </a> </li>
        </ul>
    </div>
    <h1 align="left"> Наши новости </h1>
    <p align="left"> Публикаций на странице: {{news|length}} шт. </p>
    <hr>
</div>
{% endblock preview %}

{% block table %}
    <div class="post">
        <table>
            <tr>
                <td style="font-size:22px" width="250" height="80">
                    <strong> Заголовок </strong>
                </td>
                <td style="font-size:22px" width="250">
                    <strong> Дата публикации </strong>
                </td>
                <td style="font-size:22px" width="600">
                    <strong> Содержание </strong>
                </td>
            </tr>
        </table>
    </div>
{% endblock table %}
{% block content %}
    {% if news %}
        {% for post in news %}
        <div class="post">
            <table>
            <tr>
                <td align="left" valign="top" width="250" height="80"> {{post.title|censor}} </td>
                <td align="center" valign="top" width="250"> {{post.date_create|date:'d.m.Y H:i'}} </td>  <!-- привести к нужному часовому поясу -->
                <td align="left" valign="top" width="600">
                    <div class="news_bar">
                        <p>
                            Тип публикации: {{post.get_type_article_display}}, &nbsp; &nbsp;
                            Категория:
                            {% for i in post.category.all %}
                            {{ i.get_title_display }},
                            {% endfor %} &nbsp; &nbsp;
                            Автор: {{post.user}}
                        </p>
                    </div>
                    <div>
                        {{post.article|truncatewords:20|censor}}<br>
                        <p><a href="{{post.id}}" > Читать полностью ... </a></p> <!-- Если добавить target="_blank", то будет открываться в новом окне -->
                        <p align="right">
                            <span>Рейтинг: {{post.rating}} &nbsp; &nbsp; &nbsp; &nbsp;</span>
                            {% if post.type_article == 'NW'%}
                            <span><a href="{% url 'news_update' post.id %}" style="text-decoration: none" > редактировать </a></span>
                            {% elif post.type_article == 'AR' %}
                            <span><a href="{% url 'articles_update' post.id %}" style="text-decoration: none" > редактировать </a></span>
                            {% endif %}
                        </p>
                    </div>
                </td>
            </tr>
            </table>
        </div>
        {% endfor %}
    {% else %}
        На сегодня новостей нет ... нас забанили за плагиат :))
    {% endif %}
{% endblock content %}

{% block paginator %}
<div>
    <!-- Добавляем пагинацию на страницу -->
    <!-- Информация о предыдущих страницах -->
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    <!-- Информация о текущей странице -->
    {{ page_obj.number }}

    <!-- Информация о следующих страницах -->
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

    <p>Публикации {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
{% endblock paginator %}
</div>

NewsPaper/templates/news/news_delete.html
{% extends 'news/flatpages/default.html' %}

{% block content %}
<div class="post">
<h1>Удаление новости</h1>
<hr>
{% if object.type_article == "NW" %}
<form action="" method="post">
    {% csrf_token %}
    <p>Вы действительно хотите удалить публикацию? <br><br> Заголовок: <br> "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% else %}
    <div align="left">
        <ul>
            <li> Статьи редактируются на другой странице </li>
        </ul>
    </div>
{% endif %}
</div>
{% endblock content %}

NewsPaper/templates/news/news_edit.html
{% extends 'news/flatpages/default.html' %}

{% block title %}
Форма записи
{% endblock title %}

{% block content %}
<div class="post">
<h3> Публикация/редактирование</h3>
<p style="font-size:22px"> новости </p>
<hr>
{% if object.type_article == "NW" or object.type_article is None %}
    <div align="left">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" />
        </form>
    </div>
{% else %}
    <div align="left">
        <ul>
            <li> Статьи редактируются на другой странице </li>
        </ul>
    </div>
{% endif %}
<hr>
{% if object.id is not None%}
    <p align="left"><a href="{% url 'news_delete' post.id %} " > Удалить новость </a></p>
{% endif%}
</div>
{% endblock content %}

NewsPaper/templates/news/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'news/flatpages/default.html' %}

{% load app_filters %}

<!-- Название у нас будет -->
{% block title %}
Новость
{% endblock title %}

<!-- В контенте на странице мы выводим -->
{% block content %}
<div class="post">
    <h3>{{ time_now|date:'d F Y' }}</h3>
    <hr>
    {% if post %}
        <table>
            <tr>
                <td style="font-size:22px" valign="top" width="300" height="60"></td>
                <td align="left" valign="top">
                    <div class="news_bar">
                        <p>
                            Тип публикации: {{post.get_type_article_display}}, &nbsp; &nbsp;
                            Категория:
                            {% for i in post.category.all %}
                            {{ i.get_title_display }},
                            {% endfor %} &nbsp; &nbsp;
                            Автор: {{post.user}}
                        </p>
                    </div>
                </td>
            </tr>
            <tr>
                <td style="font-size:22px" valign="top" width="300" height="80">
                    <strong> Заголовок </strong>
                </td>
                <td align="left" valign="top" height="80"> {{post.title|censor}} </td>
            </tr>
            <tr>
                <td style="font-size:22px" valign="top" width="250" height="80">
                    <strong> Дата публикации </strong>
                </td>
                <td align="left" valign="top"> {{post.date_create|date:'d.m.Y H:i:s' }} </td>
            </tr>
            <tr>
                <td style="font-size:22px" valign="top">
                    <strong> Содержание </strong>
                </td>
                <td align="left" valign="top"> {{post.article|censor}}</td>
            </tr>
        </table>
        <br>
        <hr>
        <p align="left">
            Подписаться на рассылку публикаций категории:
            {% for i in post.category.all %}
            <a href="{% url 'check_category' %}"> {{ i.get_title_display }}</a>
            {% endfor %}
        </p>
    {% else %}
        Что-то пошло не так ... тут ничего нет!
    {% endif %}
</div>
{% endblock content %}

NewsPaper/templates/news/post_created_mail.html
<!DOCTYPE html>
<html lang="en, ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% load custom_tags %}
    <p> Здравствуй {{user}}. Новая статья в твоём любимом разделе!: </p>
    <p> {{title}} </p>
    <p> {{article|truncatewords:50}} </p>
<!--    <p> <a href="{% add_domain news %}"> Смотреть </a> </p>-->
</body>
</html>

NewsPaper/templates/news/post_for_mailing_to_tasks.html
<!DOCTYPE html>
<html lang="en, ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% load custom_tags %}
    <h1> Здравствуйте! Наши статьи за прошлую неделю </h1>
    <br>
    <h3> Заголовки: </h3>
    {% for i in post %}
    <p> {{i.title|truncatewords:10}} </p>
    {% endfor %}
</body>
</html>

NewsPaper/templates/news/search.html
{% extends 'news/flatpages/default.html' %}

{% load app_filters %}
{% load custom_tags %}

{% block title %}
Поиск
{% endblock title %}

<!-- <style>
    .news_bar {
       background: #ebe4e4;
    }
    .form_label {
        font-family: Tahoma;
        font-weight: bold;
        font-size: 18px;
    }
</style> -->
{% block preview %}
<div class="post">
<h2> Поиск новостей </h2>
<form action="" method="get" >
    <!-- Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями -->
    <!-- {{ filterset.form.as_p }} -->

    {% for f in filterset.form %}
        <p><label class="form_label" for="{{f.id_for_label}}">{{f.label}}</label> {{f}} </p>
        <div>{{f.errors}}</div>
    {% endfor %}

    <!-- Добавим кнопку отправки данных формы -->
    <!--<input type="date" id="start" name="trip-start" value="2023-06-23" min="2022-01-01" max="2025-12-31" />-->
    <!-- <input
        type="datetime-local"
        id="meeting-time"
        name="meeting-time"
        value="2023-06-12T19:30"
        min="2022-06-07T00:00"
        max="2025-06-14T00:00"
    /> -->
    <input type="submit" value="Найти" />
</form>

<hr>
</div>
{% endblock preview %}
<!--
<ul>
    {% for object in object_list %}
        <li>{{ object }}</li>
    {% endfor %}
</ul>
-->

{% block table %}
<div class="post">
<table>
    <tr>
        <td style="font-size:22px" width="250" height="80"> <strong> Заголовок </strong> </td>
        <td style="font-size:22px" width="250"> <strong> Дата публикации </strong> </td>
        <td style="font-size:22px"> <strong> Содержание </strong> </td>
    </tr>
</table>
</div>
{% endblock table %}

{% block content %}
{% if search %}
    {% for post in search %}
    <div class="post">
    <table>
    <tr>
        <td align="left" valign="top" width="250" height="80"> {{post.title|censor}} </td>
        <td align="center" valign="top" width="250"> {{post.date_create|date:'d.m.Y H:i'}} </td>  <!-- привести к нужному часовому поясу -->
        <td align="left" valign="top">
            <div>
                <p class="news_bar">
                    Тип публикации: {{post.get_type_article_display}}, &nbsp; &nbsp;
                    Категория:
                    {% for i in post.category.all %}
                    {{ i.get_title_display }},
                    {% endfor %} <br>
                    Автор: {{post.user}}
                </p>
            </div>
            <div>
                {{post.article|truncatewords:20|censor}}<br>
                <p><a href="../{{post.id}}" > читать полностью ... </a></p> <!-- если добавить target="_blank", то будет открываться в новом окне -->
            </div>
        </td>
    </tr>
    </table>
    </div>
    {% endfor %}
{% else %}
    <div class="post">
        Что-то пошло не так ... тут ничего нет!
    </div>
{% endif %}
{% endblock content %}

{% block paginator %}
<div class="post">
{% if page_obj.has_previous %}
    <a href="?{% url_replace page=1 %}">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

    <p>Публикации {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
</div>
{% endblock paginator %}